language: java
dist: trusty
sudo: false

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

addons:
  sonarcloud:
    organization: "configcat"
    token:
      secure: "LU1S5sliPfPvJT0bP8/obDYhf0qckHtdcuDZ7NWHaQGOPV8zt1vaqRiIa0Rei+/V47p9xsniEWQjYRRZv+BHs86fU72NoVgH/6GJGz5B/FeHdyr1FC6bW8sguGxsKJKKNKu8JQwwDzys0S5J9eo8zmBl8Q30gwvhGlogTgSwvSKQOgM5l3jdZLU/E7I7sg45XxIsVZeb6Q/ZOyjoLRd2gHqLSz4buP3/Dl9MO8dJ0LhhhtuNbNpgw9T18as83GaHYkYReL1aXVusuqx3JXcg/uIEpi9cOujKgLuBez4VOFlCBiTm6N46l+onEslnnN5Sp9CXe7vDjx9ZnuyWF3yhN8hcfvaa+4MxJW90Z7kvhtBIr60hNlI0qiDuhWTIuhb3K0Fu/UPTAx7EZMADHPLxuLLg8wR16glzqehLoRZfdL1J+9mMb/NrnPVIL5yFwe4UgYTYUE33yreq4mUQ0ujOW9KqhBJRgj0IKtLU9rYVG5Z6Mw8rbfRDSdTeaSKV1B/sHmZefQvqSb1OnvpPGJbi8HA6+cDwhSy/ZbMCBhYAaVlw8jjTGOXr+k+nwkpiyZaE9f7Z7AO0TKH8a6S+7f3HcdlAPaNQBfuX6/7M+LVzb2ckDi6OwuJmxkwBLfibBxFkq+/5PkUlrriIr5Ji/y1m5vDdaRglg3D4njEGom4OLFI="

before_install:
- chmod +x gradlew
script: "./gradlew test"

stages:
- test
- coverage
- sonar
- name: snapshot
  if: tag IS blank
- name: release
  if: tag =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/

jobs:
  include:
  - stage: coverage
    script:
    - "./gradlew check"
    - bash <(curl -s https://codecov.io/bash)
    jdk: oraclejdk8
  - stage: sonar
    script:
    - ./gradlew sonarqube
    jdk: oraclejdk8
  - stage: snapshot
    script: "./gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8
  - stage: release
    script: "./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dsigning.pass=$SIGN_PASS -Dbuild.number=$TRAVIS_BUILD_NUMBER"
    jdk: oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/repositories/"

env:
  global:
  - secure: PRZ2mCtos+dalxQWdbxnA7oTqOV4hAPuNJxHN6xgdfP+hJjfqw02M5hMFdTQ1Cq366d9pBUiwVT6U7uP+Y5UgrAdEMMLgendIvm+Uf+04YLUk1w+tRVHfBTPbZp5yG33+6s5aAPM30tPf6dGvoG+iJv3WyeNea45Exsjv39B5aoCzd/TpIcWDCaEmx+XL1RZDExh2AWIvDYW/PhXSvITQvzRAXh8IZY9EBL3A2hrecaQ+YAS7zzQjorZdOMwJNvLXVUV/SR/N8fptAVnHbpIgiw3peT62LHcetmxAoQqByJb03VJBeCZhv6l8PzXwK22wfhh7B7HumN+XmJl50uZiO8ng8mldctaAjlUha/y/o6g/NwHX6DDTT0UmljH1+9t/71dAt6bZMOQXFddrIzLLGQOkXwqY87hdqY7y3AoKl3O8LnJwpFcPE4QsrwWS3uL/7ntDaerD04gSnCSHV54rJaKYRV1CmkmTsPL3xXUqHkp5lp/3gRcBPXYvga9PbUSW68jX13IS5kbMFg+nXBHvznm8xnjpfxarMzGBFXxG5B8MUhNrCiJ+BHhtbl5wl4wOfPLJToQCLdI5EmcyjXE3dQMntZbbXlcoN0BkGKzWTtDm7VJ8LQWrdOLbpzFMENHuiz7IXl/c9IVLHtO3ls/sWZXzgfZgRCYLm7bZd2nq0M=
  - secure: CYcz67QCBvetSXuf89sQBr0bOsBdIXu9vIadeaRUkNGk/8weXPrlrQyy1XEd04COiwRgLf/qYVWwWxyRC2QSpZAT3ShNERCp2pTaumB1IX6AMkxx/iwvZI4VbHJh/PacUMoV2mlx/geItHQzy3Vkt5+5YqdD4ZjFEg11KQGdHEXDF3d98/+qCNqUmBXcgha1MxNeIBCnKG9DFLXjVP6YIgvwGamDCKenB5OixsEeXiis8tRko8t5p0oNjHllJfM/gZsTeo5tNRGgLbaNj2+l8JouZcN30D75iBULjIro3GE6rD/HEriGlBD/Pb9PBXL7ZZT2zghfHSp8lGq10Pnjsbv2nobrucWrc4g3d1pz1/ZOBF9pSDFwGNMt6y6F/YVfmSL6kMYYxGXvo5k9XrPDwPEmrZoSuJ0QjlkgwyhGQBTEqgl/CH2RD7hYhzO5FGfQgByMqdy70NWcJp+7H903dooYcccS/b+fi0ETWAzltwg9cAce1waypdGJlcjN2rkgvU9zWnmoi9x6lYcjBdEOMMCCl6Pj3xkK+C6uB9MCzTskQR9qfFCZgMPh4kLNcBLd1PMuwLFAWi+q/wI2wDh1oMdXegcknxtTu8+UNlkFY2t/ewjL/g0AhA4cajFDtS9qHvN4HaeSL/yvTnViyg8El3OPml/++fP2pA61vrQ/kvg=
  - secure: ZigPI/0UrT8lexi7YkEHNky1Yl6Bs/V7CTjbTJImLOf7tElafinkieTSJbItQWIWYS9lH3OebJkPC9SrLW54XDPsa58EJZx8GKKwBypkEBpOThBwAYOjIZWPYLv5iNI9usDM5wvL3HrgScbtH7dm7UgflOIngUAYone+q1crzD4E3zcSLnBP2G9jgw+fDqQlDWHus5QfLkzgJpLPOnq44s3AMjyfqaTWWD/aQ6+tCNKmCEIWmZpxQ1zC+4e4StltT8BjFQ9k1UEgJrVmbNAx4PU6F+5drl5Bx5tdAK9yCFOX0K01PMh7dwz0hqbXWtDi0dQhRnviGh13zBTVoXkpQ3AJgbEYi1W7HQ7AXCQQcrE5lPEl6LkqZXwYKs1E9dKdsxH94Qv4SeAIHN3KZc2B/CUo9wZ+sXn0Ftg7IHq3d+7ovSdJ8eFezrdd1LwPr59r23Qo3YlphRPs6bWjr/GcWMjldjcnFbOCO9loIiCj7hZzRrPWU8IPEfSeAeJNt23EX05mW80m3BRL1FvCqfSkXDlTDKREPdLe97vlT2XdyZ57TnYWaSFInr2RXaEqSgAuwkrkvXNRncbh0F/RGEvjxFnuFv8Dx6bbqfdj+7KYUatLC0OybnUsCvF9owNaqdJHRslWWCX+5+rr2JRD7Q2Io8Srb38RLkrAARwrnxFxa3o=
